finicio = open('fichero.txt', 'w')
finicio.write('hola buenas noches')
finicio.write('\nque tal?')
#finicio.close()
finicio = open('fichero.txt', 'r')
#print(finicio.read())
lineas = print(finicio.readlines())
print(lineas)
finicio.close()